

export const  GET_ALL_ITEMS_REQUEST = "GET_ALL_ITEMS_REQUEST";
export const  GET_ALL_ITEMS_SUCSESS = "GET_ALL_ITEMS_SUCSESS";
export const  GET_ALL_ITEMS_RFAILURE = "GET_ALL_ITEMS_RFAILURE";

export const  PATCH_ITEM_REQUEST = "PATCH_ITEM_REQUEST";
export const  PATCH_ITEM_SUCSESS = "PATCH_ITEM_SUCSESS";
export const  PATCH_ITEM_RFAILURE = "PATCH_ITEM_RFAILURE";

export const  POST_ITEM_REQUEST = "POST_ITEM_REQUEST";
export const  POST_ITEM_SUCSESS = "POST_ITEM_SUCSESS";
export const  POST_ITEM_RFAILURE = "POST_ITEM_RFAILURE";

export const DAY_TO_GET_API="Sheet1"; 